#!/usr/bin/env python3
"""Best-effort accent restoration for the 4 French + 1 Italian QOuLiPo texts.

Curated word-level replacement dictionary covering the most frequent
French/Italian accented forms. Applied as whole-word replacements
(case-preserving) so common words like 'a' (verb avoir) → 'à' only fire
when surrounded by word boundaries.

Limitations: this is *first-pass* restoration. Homographs (avoir-3rd-sing
'a' vs preposition 'à') may be miscategorised in rare contexts.
A native-speaker review is still recommended before final publication.
"""
import re
from pathlib import Path

# ── French dictionary ────────────────────────────────────────────────────
# Format: ascii_form → accented_form
# Whole-word, case-preserving (lowercase keys; we handle Title-case at apply time).
FR = {
    # Function words / common adverbs that are unambiguously accented
    "a": None,  # 'a' is ambiguous (avoir vs à); skip whole-word; use phrase rules instead
    "deja": "déjà",
    "ou": None,  # ambiguous (or vs où); use phrase rules
    "tres": "très",
    "apres": "après",
    "etre": "être",
    "ete": "été",
    "etes": "êtes",
    "etais": "étais",
    "etait": "était",
    "etions": "étions",
    "etiez": "étiez",
    "etaient": "étaient",
    "meme": "même",
    "memes": "mêmes",
    "ca": "ça",
    "celle": "celle",  # no change
    "celebre": "célèbre",
    "celebres": "célèbres",
    "decembre": "décembre",
    "fevrier": "février",
    "ecole": "école",
    "ecoles": "écoles",
    "ecrit": "écrit",
    "ecrite": "écrite",
    "ecrits": "écrits",
    "ecrites": "écrites",
    "ecrivain": "écrivain",
    "ecriture": "écriture",
    "elementaire": "élémentaire",
    "elementaires": "élémentaires",
    "elements": "éléments",
    "element": "élément",
    "elegance": "élégance",
    "elegant": "élégant",
    "egal": "égal",
    "egale": "égale",
    "egalement": "également",
    "egales": "égales",
    "edifice": "édifice",
    "edition": "édition",
    "elephant": "éléphant",
    "epoque": "époque",
    "epreuve": "épreuve",
    "etude": "étude",
    "etudes": "études",
    "etudiant": "étudiant",
    "etudiants": "étudiants",
    "eveil": "éveil",
    "evenement": "événement",
    "evidence": "évidence",
    "evident": "évident",
    "evidente": "évidente",
    "francais": "français",
    "francaise": "française",
    "frere": "frère",
    "freres": "frères",
    "premiere": "première",
    "premieres": "premières",
    "derniere": "dernière",
    "dernieres": "dernières",
    "lumiere": "lumière",
    "lumieres": "lumières",
    "matiere": "matière",
    "matieres": "matières",
    "maniere": "manière",
    "manieres": "manières",
    "barriere": "barrière",
    "barrieres": "barrières",
    "frontiere": "frontière",
    "frontieres": "frontières",
    "siecle": "siècle",
    "siecles": "siècles",
    "regle": "règle",
    "regles": "règles",
    "reglement": "règlement",
    "regne": "règne",
    "regnes": "règnes",
    "decret": "décret",
    "decrets": "décrets",
    "modele": "modèle",
    "modeles": "modèles",
    "probleme": "problème",
    "problemes": "problèmes",
    "systeme": "système",
    "systemes": "systèmes",
    "theme": "thème",
    "themes": "thèmes",
    "theoreme": "théorème",
    "theoremes": "théorèmes",
    "schema": "schéma",
    "schemas": "schémas",
    "scene": "scène",
    "scenes": "scènes",
    "ferme": "ferme",  # ambiguous
    "preface": "préface",
    "prefere": "préfère",
    "preferer": "préférer",
    "presence": "présence",
    "present": "présent",
    "presente": "présente",
    "presentes": "présentes",
    "presents": "présents",
    "presente": "présenté",  # past participle; ambiguous
    "presentation": "présentation",
    "preparer": "préparer",
    "prepare": "préparé",  # ambiguous (prep. vs presented)
    "professeur": "professeur",  # no change (no accents)
    "professeurs": "professeurs",
    "professionnel": "professionnel",
    "professionnelle": "professionnelle",
    "etablir": "établir",
    "etabli": "établi",
    "etablie": "établie",
    "etablissement": "établissement",
    "etablissements": "établissements",
    "etat": "état",
    "etats": "états",
    "experience": "expérience",
    "experiences": "expériences",
    "experiment": "expériment",
    "experimentation": "expérimentation",
    "complete": "complète",
    "completes": "complètes",
    "complet": "complet",
    "completement": "complètement",
    "concrete": "concrète",
    "concretes": "concrètes",
    "concret": "concret",
    "concretement": "concrètement",
    "discrete": "discrète",
    "discretes": "discrètes",
    "discret": "discret",
    "discretement": "discrètement",
    "secrete": "secrète",
    "secretes": "secrètes",
    "secret": "secret",
    "litterature": "littérature",
    "litteraire": "littéraire",
    "litteraires": "littéraires",
    "philosophe": "philosophe",  # no change
    "philosophie": "philosophie",
    "philosophique": "philosophique",
    "physique": "physique",  # no change
    "geometrie": "géométrie",
    "geometrique": "géométrique",
    "geometriques": "géométriques",
    "metaphysique": "métaphysique",
    "mecanique": "mécanique",
    "raison": "raison",
    "interet": "intérêt",
    "interets": "intérêts",
    "tete": "tête",
    "tetes": "têtes",
    "fete": "fête",
    "fetes": "fêtes",
    "bete": "bête",
    "betes": "bêtes",
    "pret": "prêt",
    "prete": "prête",
    "prets": "prêts",
    "pretes": "prêtes",
    "arrete": "arrête",
    "arretes": "arrêtes",
    "arreter": "arrêter",
    "honnete": "honnête",
    "honnetes": "honnêtes",
    "etrange": "étrange",
    "etranges": "étranges",
    "etranger": "étranger",
    "etrangers": "étrangers",
    "etrangere": "étrangère",
    "etrangeres": "étrangères",
    "celui": "celui",  # no change
    "ceci": "ceci",  # no change
    "lecon": "leçon",
    "lecons": "leçons",
    "garcon": "garçon",
    "garcons": "garçons",
    "francois": "François",  # name; case handled separately
    "facon": "façon",
    "facons": "façons",
    "recu": "reçu",
    "recue": "reçue",
    "recus": "reçus",
    "recues": "reçues",
    "apercu": "aperçu",
    "apercus": "aperçus",
    "decu": "déçu",
    "decue": "déçue",
    "concu": "conçu",
    "concue": "conçue",
    "concevoir": "concevoir",
    "deuxieme": "deuxième",
    "troisieme": "troisième",
    "quatrieme": "quatrième",
    "cinquieme": "cinquième",
    "sixieme": "sixième",
    "septieme": "septième",
    "huitieme": "huitième",
    "neuvieme": "neuvième",
    "dixieme": "dixième",
    "onzieme": "onzième",
    "douzieme": "douzième",
    "seizieme": "seizième",
    "vingtieme": "vingtième",
    "centieme": "centième",
    "millieme": "millième",
    "millier": "millier",
    "milliers": "milliers",
    "annee": "année",
    "annees": "années",
    "journee": "journée",
    "journees": "journées",
    "soiree": "soirée",
    "soirees": "soirées",
    "matinee": "matinée",
    "matinees": "matinées",
    "annee": "année",
    "musee": "musée",
    "musees": "musées",
    "lycee": "lycée",
    "lycees": "lycées",
    "destinee": "destinée",
    "destinees": "destinées",
    "armee": "armée",
    "armees": "armées",
    "idee": "idée",
    "idees": "idées",
    "verite": "vérité",
    "verites": "vérités",
    "realite": "réalité",
    "realites": "réalités",
    "qualite": "qualité",
    "qualites": "qualités",
    "quantite": "quantité",
    "quantites": "quantités",
    "societe": "société",
    "societes": "sociétés",
    "facilite": "facilité",
    "humanite": "humanité",
    "humanites": "humanités",
    "etrange": "étrange",
    "celebrer": "célébrer",
    "celebre": "célèbre",
    "ferocite": "férocité",
    "verifier": "vérifier",
    "verifie": "vérifié",
    "verifiee": "vérifiée",
    "verifies": "vérifiés",
    "verification": "vérification",
    "preciser": "préciser",
    "precis": "précis",
    "precise": "précise",
    "precision": "précision",
    "precisement": "précisément",
    "selection": "sélection",
    "selections": "sélections",
    "selectionner": "sélectionner",
    "demonstration": "démonstration",
    "demonstrations": "démonstrations",
    "deduction": "déduction",
    "deductions": "déductions",
    "induction": "induction",
    "inductions": "inductions",
    "deduire": "déduire",
    "deduit": "déduit",
    "deduite": "déduite",
    "verifie": "vérifié",
    "epreuves": "épreuves",
    "etage": "étage",
    "etages": "étages",
    "etranger": "étranger",
    "ferme": "ferme",
    "celle-ci": "celle-ci",
    "lui-meme": "lui-même",
    "elle-meme": "elle-même",
    "moi-meme": "moi-même",
    "toi-meme": "toi-même",
    "soi-meme": "soi-même",
    "eux-memes": "eux-mêmes",
    "elles-memes": "elles-mêmes",
    "nous-memes": "nous-mêmes",
    "vous-memes": "vous-mêmes",
    "ame": "âme",
    "ames": "âmes",
    "controle": "contrôle",
    "controles": "contrôles",
    "controler": "contrôler",
    "role": "rôle",
    "roles": "rôles",
    "hote": "hôte",
    "hotes": "hôtes",
    "votre": "votre",
    "notre": "notre",
    "votres": "vôtres",  # rare
    "notres": "nôtres",  # rare
    "cote": "côté",
    "cotes": "côtés",
    "tot": "tôt",
    "plutot": "plutôt",
    "aussitot": "aussitôt",
    "bientot": "bientôt",
    "diplome": "diplôme",
    "diplomes": "diplômes",
    "depot": "dépôt",
    "depots": "dépôts",
    "syndrome": "syndrome",  # no accent in modern French
    "drole": "drôle",
    "droles": "drôles",
    "icone": "icône",
    "icones": "icônes",
    "cone": "cône",
    "cones": "cônes",
    "zone": "zone",
    "zones": "zones",
    "fenetre": "fenêtre",
    "fenetres": "fenêtres",
    "naitre": "naître",
    "connaitre": "connaître",
    "connait": "connaît",
    "paraitre": "paraître",
    "parait": "paraît",
    "apparaitre": "apparaître",
    "apparait": "apparaît",
    "disparaitre": "disparaître",
    "disparait": "disparaît",
    "geometre": "géomètre",
    "geometres": "géomètres",
    "interieur": "intérieur",
    "interieurs": "intérieurs",
    "interieure": "intérieure",
    "interieures": "intérieures",
    "exterieur": "extérieur",
    "exterieurs": "extérieurs",
    "exterieure": "extérieure",
    "exterieures": "extérieures",
    "superieur": "supérieur",
    "superieurs": "supérieurs",
    "superieure": "supérieure",
    "superieures": "supérieures",
    "inferieur": "inférieur",
    "inferieurs": "inférieurs",
    "inferieure": "inférieure",
    "inferieures": "inférieures",
    "anterieur": "antérieur",
    "anterieurs": "antérieurs",
    "anterieure": "antérieure",
    "anterieures": "antérieures",
    "posterieur": "postérieur",
    "posterieurs": "postérieurs",
    "posterieure": "postérieure",
    "posterieures": "postérieures",
    "ulterieur": "ultérieur",
    "ulterieurs": "ultérieurs",
    "ulterieure": "ultérieure",
    "ulterieures": "ultérieures",
    "necessaire": "nécessaire",
    "necessaires": "nécessaires",
    "necessairement": "nécessairement",
    "necessite": "nécessité",
    "necessites": "nécessités",
    "general": "général",
    "generaux": "généraux",
    "generale": "générale",
    "generales": "générales",
    "generalement": "généralement",
    "particulier": "particulier",
    "particuliers": "particuliers",
    "particuliere": "particulière",
    "particulieres": "particulières",
    "particulierement": "particulièrement",
    "regulier": "régulier",
    "reguliers": "réguliers",
    "reguliere": "régulière",
    "regulieres": "régulières",
    "regulierement": "régulièrement",
    "irregulier": "irrégulier",
    "irreguliers": "irréguliers",
    "irreguliere": "irrégulière",
    "irregulieres": "irrégulières",
    "decouverte": "découverte",
    "decouvertes": "découvertes",
    "decouvrir": "découvrir",
    "decouvre": "découvre",
    "decouvert": "découvert",
    "decouverte": "découverte",
    "definition": "définition",
    "definitions": "définitions",
    "definir": "définir",
    "defini": "défini",
    "definie": "définie",
    "definis": "définis",
    "definies": "définies",
    "definitif": "définitif",
    "definitifs": "définitifs",
    "definitive": "définitive",
    "definitives": "définitives",
    "definitivement": "définitivement",
    "developpement": "développement",
    "developpements": "développements",
    "developper": "développer",
    "developpe": "développé",
    "developpee": "développée",
    "developpes": "développés",
    "developpees": "développées",
    "evidence": "évidence",
    "evidences": "évidences",
    "evident": "évident",
    "evidente": "évidente",
    "evidents": "évidents",
    "evidentes": "évidentes",
    "evidemment": "évidemment",
    "extra": "extra",
    "frere": "frère",
    "freres": "frères",
    "soeur": "sœur",
    "soeurs": "sœurs",
    "coeur": "cœur",
    "coeurs": "cœurs",
    "oeuvre": "œuvre",
    "oeuvres": "œuvres",
    "oeuf": "œuf",
    "oeufs": "œufs",
    "boeuf": "bœuf",
    "noeud": "nœud",
    "noeuds": "nœuds",
    "voeu": "vœu",
    "voeux": "vœux",
    "ile": "île",
    "iles": "îles",
    "agreable": "agréable",
    "agreables": "agréables",
    "moliere": "Molière",
    "voltaire": "Voltaire",
    "rousseau": "Rousseau",
    "celes": "célés",
    "ces": "ces",
    "ferme": "ferme",
    "donnees": "données",
    "donnee": "donnée",
    "donne": "donné",
    "destinee": "destinée",
    "destin": "destin",
    "etre": "être",
    "etres": "êtres",
    "ane": "âne",
    "anes": "ânes",
    "chateau": "château",
    "chateaux": "châteaux",
    "tache": "tâche",
    "taches": "tâches",
    "graveur": "graveur",
    "ame": "âme",
    "ames": "âmes",
    "naivete": "naïveté",
    "naif": "naïf",
    "naive": "naïve",
    "noel": "Noël",
    "haine": "haine",  # no change
    "thai": "thaï",  # rare
    "fenetre": "fenêtre",
    "embeter": "embêter",
    "embete": "embête",
    "tete-a-tete": "tête-à-tête",
    "vis-a-vis": "vis-à-vis",
    "a la": "à la",  # phrase
    "a l'": "à l'",
    "a un": "à un",
    "a une": "à une",
    "a partir": "à partir",
    "a peu": "à peu",
    "a peine": "à peine",
    "a propos": "à propos",
    "a cote": "à côté",
    "ou bien": "ou bien",  # 'ou' here = or
    "la ou": "là où",  # adv. la → là
    "d'ou": "d'où",
    "ou que": "où que",
    "par ou": "par où",
    "n'a": "n'a",
    "n'avait": "n'avait",
    "n'ont": "n'ont",
    "n'est": "n'est",
    "n'etait": "n'était",
    "celui-la": "celui-là",
    "celle-la": "celle-là",
    "ceux-la": "ceux-là",
    "celles-la": "celles-là",
    "voila": "voilà",
    "deja": "déjà",
    "des que": "dès que",
    "des lors": "dès lors",
    "ici-bas": "ici-bas",
    "la-bas": "là-bas",
    "la-haut": "là-haut",
    "la-dessus": "là-dessus",
    "par la": "par là",
    "ca et la": "çà et là",
    "jusqu'a": "jusqu'à",
    "jusque-la": "jusque-là",
    "au-dela": "au-delà",
    "au dela": "au-delà",
    "par-dela": "par-delà",
    "en deca": "en deçà",
    "deja-la": "déjà-là",
    "Pere": "Père",
    "pere": "père",
    "peres": "pères",
    "mere": "mère",
    "meres": "mères",
    "fils": "fils",
    "vrai": "vrai",
    "vraie": "vraie",
    "deuxieme": "deuxième",
    "vue": "vue",
    "vues": "vues",
    "tableau": "tableau",
    "tableaux": "tableaux",
    "Pari": "Pari",  # name
    "Pasqal": "Pasqal",  # name
    "Pascal": "Pascal",  # name
    "Bibliotheque": "Bibliothèque",
    "bibliotheque": "bibliothèque",
    "bibliotheques": "bibliothèques",
    "Menil": "Ménil",
    "Andre": "André",
    "Charlemagne": "Charlemagne",  # no change
    "Strasbourg": "Strasbourg",  # no change
    "Geneve": "Genève",
    "Liege": "Liège",
    "Quebec": "Québec",
    "Montreal": "Montréal",
    "perdre": "perdre",
    "perdrai": "perdrai",
    "perdrais": "perdrais",
    "perdrait": "perdrait",
    "perdrions": "perdrions",
    "perdriez": "perdriez",
    "perdraient": "perdraient",
    "Carthage": "Carthage",
    "egout": "égout",
    "egouts": "égouts",
    "annee": "année",
    "vraiment": "vraiment",
    "fevrier": "février",
    "Fevrier": "Février",
    "janvier": "janvier",
    "octobre": "octobre",
    "novembre": "novembre",
    "decembre": "décembre",
    "Decembre": "Décembre",
    "ferai": "ferai",
    "ferais": "ferais",
    "ferait": "ferait",
    "ferions": "ferions",
    "feriez": "feriez",
    "feraient": "feraient",
    "etudier": "étudier",
    "etudie": "étudie",
    "etudies": "études",  # ambiguous: verb vs noun
    "etudie": "étudié",
    "etudies": "étudiés",
    "etudiee": "étudiée",
    "etudiees": "étudiées",
    "trahi": "trahi",
    "trahie": "trahie",
    "trahir": "trahir",
    "trahis": "trahis",
    "trahies": "trahies",
}

# Phrase-level rules (longer first; substring-replaced; case-sensitive)
FR_PHRASES = [
    ("nottre", "nôtre"),  # typo guard
    ("c'est-a-dire", "c'est-à-dire"),
    ("face-a-face", "face-à-face"),
    ("a-cote", "à-côté"),
]

# ── Italian dictionary ──────────────────────────────────────────────────
IT = {
    # Common Italian accents
    "perche": "perché",
    "Perche": "Perché",
    "poiche": "poiché",
    "benche": "benché",
    "siccome": "siccome",
    "anche": "anche",  # no change
    "cosi": "così",
    "Cosi": "Così",
    "pero": "però",
    "Pero": "Però",
    "puo": "può",
    "Puo": "Può",
    "piu": "più",
    "Piu": "Più",
    "gia": "già",
    "Gia": "Già",
    "qua": "qua",  # no change
    "qui": "qui",  # no change
    "se": "se",  # no change
    "si": "sì",  # ambiguous: reflexive 'si' vs adverb 'sì'; SKIP from word-level
    "no": "no",  # no change
    "e": "è",  # ambiguous: conjunction 'e' vs verb 'è'; SKIP from word-level
    "sara": "sarà",
    "Sara": "Sarà",
    "saro": "sarò",
    "Saro": "Sarò",
    "sarei": "sarei",
    "verra": "verrà",
    "Verra": "Verrà",
    "andra": "andrà",
    "Andra": "Andrà",
    "potra": "potrà",
    "vorra": "vorrà",
    "dovra": "dovrà",
    "fara": "farà",
    "Fara": "Farà",
    "stara": "starà",
    "trovera": "troverà",
    "rimarra": "rimarrà",
    "darai": "darai",
    "darei": "darei",
    "perdera": "perderà",
    "vedra": "vedrà",
    "saprà": "saprà",
    "leggera": "leggerà",
    "scrivera": "scriverà",
    "lo": "lo",
    "puo": "può",
    "abbastanza": "abbastanza",
    "abbastenza": "abbastanza",
    "mai": "mai",  # no change
    "ne": "né",  # ambiguous (pronoun/adverb né); SKIP whole-word
    "era": "era",  # no change
    "tre": "tre",  # no change
    "trentatre": "trentatré",
    "tristezza": "tristezza",
    "comunita": "comunità",
    "Comunita": "Comunità",
    "citta": "città",
    "Citta": "Città",
    "civilta": "civiltà",
    "qualita": "qualità",
    "quantita": "quantità",
    "umanita": "umanità",
    "felicita": "felicità",
    "diversita": "diversità",
    "verita": "verità",
    "Verita": "Verità",
    "carita": "carità",
    "liberta": "libertà",
    "Liberta": "Libertà",
    "novita": "novità",
    "realta": "realtà",
    "Realta": "Realtà",
    "facolta": "facoltà",
    "specialita": "specialità",
    "responsabilita": "responsabilità",
    "possibilita": "possibilità",
    "necessita": "necessità",
    "Necessita": "Necessità",
    "autorita": "autorità",
    "facilita": "facilità",
    "felicita": "felicità",
    "antichita": "antichità",
    "Antichita": "Antichità",
    "modernita": "modernità",
    "rapidita": "rapidità",
    "tranquillita": "tranquillità",
    "verità": "verità",
    "città": "città",  # already accented
    "ahime": "ahimè",
    "caffe": "caffè",
    "Caffe": "Caffè",
    "te": "tè",  # ambiguous (you vs tea); SKIP
    "tre": "tre",
    "vita": "vita",  # no change
    "io": "io",  # no change
    "tu": "tu",  # no change
    "noi": "noi",
    "voi": "voi",
    "loro": "loro",
    "quale": "quale",
    "quali": "quali",
    "Maestà": "Maestà",
    "maesta": "maestà",
    "diletto": "diletto",
    "subito": "subito",
    "neanche": "neanche",
    "appena": "appena",
    "ovunque": "ovunque",
    "dovunque": "dovunque",
    "comunque": "comunque",
    "qualcuno": "qualcuno",
    "qualcosa": "qualcosa",
    "ognuno": "ognuno",
    "ognuna": "ognuna",
    "ciascuno": "ciascuno",
    "nessuno": "nessuno",
    "qualunque": "qualunque",
    "qualsiasi": "qualsiasi",
    "papa": "papà",  # ambiguous (pope vs father), but in narrative usually papà
    "Papa": "Papà",
    "Andra": "Andrà",
    "Lassu": "Lassù",
    "lassu": "lassù",
    "laggiu": "laggiù",
    "quaggiu": "quaggiù",
    "su": "su",  # no change
    "giu": "giù",
    "Giu": "Giù",
    "nonostante": "nonostante",
    "tuttavia": "tuttavia",
}

# Italian phrase rules
IT_PHRASES = [
    (" e' ", " è "),  # apostrophe-style accent compensation
    (" e'", " è"),
    ("E'", "È"),
]

# ── Application ─────────────────────────────────────────────────────────
def apply_dict(text, d):
    """Apply word-level dictionary, case-preserving."""
    # Build regex on lowercase keys, applying lowercase-only here.
    keys = sorted([k for k, v in d.items() if v is not None and k != v], key=len, reverse=True)
    if not keys:
        return text
    pat = re.compile(r"\b(" + "|".join(re.escape(k) for k in keys) + r")\b")
    def sub(m):
        word = m.group(0)
        lo = word.lower()
        repl = d.get(lo)
        if repl is None:
            return word
        # Preserve case
        if word.isupper():
            return repl.upper()
        if word[0].isupper():
            return repl[0].upper() + repl[1:]
        return repl
    # Handle exact-case versions first (for Title-cased dict entries)
    # Apply general (case-insensitive) substitution
    return pat.sub(sub, text)


def apply_phrases(text, phrases):
    for src, dst in phrases:
        text = text.replace(src, dst)
    return text


def restore(folder, dict_, phrases):
    src = Path(f"corpus/qoulipo/{folder}/source")
    files = sorted(src.glob("*.txt"))
    n_changed = 0
    n_diff = 0
    for f in files:
        orig = f.read_text(encoding="utf-8")
        out = apply_dict(orig, dict_)
        out = apply_phrases(out, phrases)
        if out != orig:
            f.write_text(out, encoding="utf-8")
            n_changed += 1
            n_diff += sum(1 for a, b in zip(orig, out) if a != b)
    return n_changed, len(files), n_diff


def main():
    print("Restoring French accents (4 folders)")
    for folder in ("jumeaux_fr", "partition_du_texte", "pascal_apocryphe", "pascal_apocryphe_scholia"):
        n, total, n_diff = restore(folder, FR, FR_PHRASES)
        print(f"  {folder}: {n}/{total} files updated, {n_diff} char-diffs")
    print("\nRestoring Italian accents (1 folder)")
    n, total, n_diff = restore("castello_49_destini", IT, IT_PHRASES)
    print(f"  castello_49_destini: {n}/{total} files updated, {n_diff} char-diffs")


if __name__ == "__main__":
    main()
